[default]
address = "127.0.0.1"
port = 8000
base_path = "/"

[default.cache]
mode = "Internal"
max_age = 30
root = "data"
use_stale = 3600

[default.connection]
endpoint = "https://some_service.io"

[default.creds]
access_key = "some_key"
secret_key = "some_secret"
